2024-11-05 08:28:00,933 - INFO - Connecting to map hub
2024-11-05 08:28:01,836 - INFO - Connection successful
2024-11-05 08:28:01,836 - INFO - Shifting any traps that indicated the coordinates should not be included
2024-11-05 08:28:02,291 - ERROR - There was an exception
Traceback (most recent call last):
  File "/usr/share/miniconda/envs/trapper_env/lib/python3.9/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/share/miniconda/envs/trapper_env/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/share/miniconda/envs/trapper_env/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/share/miniconda/envs/trapper_env/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/miniconda/envs/trapper_env/lib/python3.9/site-packages/arcgis/gis/_impl/_con/_connection.py", line 986, in _handle_response
    data = resp.json()
  File "/usr/share/miniconda/envs/trapper_env/lib/python3.9/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/trapper-data-reporting/trapper-data-reporting/trapper_data_collection/trapper_data_modification.py", line 18, in run_app
    traps.shift_traps()
  File "/home/runner/work/trapper-data-reporting/trapper-data-reporting/trapper_data_collection/trapper_data_modification.py", line 89, in shift_traps
    traps_fset = traps_flayer.query(where='INCLUDE_COORDINATES=\'NO\'')
  File "/usr/share/miniconda/envs/trapper_env/lib/python3.9/site-packages/arcgis/features/layer.py", line 2206, in query
    return _query._common_query(
  File "/usr/share/miniconda/envs/trapper_env/lib/python3.9/site-packages/arcgis/_impl/common/_query.py", line 69, in _common_query
    params = _create_parameters(
  File "/usr/share/miniconda/envs/trapper_env/lib/python3.9/site-packages/arcgis/_impl/common/_query.py", line 220, in _create_parameters
    if getattr(layer, "_is_3d", None):
  File "/usr/share/miniconda/envs/trapper_env/lib/python3.9/site-packages/arcgis/features/layer.py", line 101, in _is_3d
    if "infoFor3D" in self.properties and self.properties.infoFor3D is not None:
  File "/usr/share/miniconda/envs/trapper_env/lib/python3.9/site-packages/arcgis/gis/__init__.py", line 18729, in properties
    self._hydrate()
  File "/usr/share/miniconda/envs/trapper_env/lib/python3.9/site-packages/arcgis/gis/__init__.py", line 18766, in _hydrate
    self._refresh()
  File "/usr/share/miniconda/envs/trapper_env/lib/python3.9/site-packages/arcgis/gis/__init__.py", line 18717, in _refresh
    raise e
  File "/usr/share/miniconda/envs/trapper_env/lib/python3.9/site-packages/arcgis/gis/__init__.py", line 18706, in _refresh
    dictdata = self._con.post(
  File "/usr/share/miniconda/envs/trapper_env/lib/python3.9/site-packages/arcgis/gis/_impl/_con/_connection.py", line 1526, in post
    return self._handle_response(
  File "/usr/share/miniconda/envs/trapper_env/lib/python3.9/site-packages/arcgis/gis/_impl/_con/_connection.py", line 989, in _handle_response
    raise Exception(resp.text)
Exception: <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>404 - File or directory not found.</title>
<style type="text/css">
<!--
body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
fieldset{padding:0 15px 10px 15px;} 
h1{font-size:2.4em;margin:0;color:#FFF;}
h2{font-size:1.7em;margin:0;color:#CC0000;} 
h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} 
#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
background-color:#555555;}
#content{margin:0 0 0 2%;position:relative;}
.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
-->
</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>404 - File or directory not found.</h2>
  <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
 </fieldset></div>
</div>
</body>
</html>

2024-11-05 08:28:02,295 - INFO - Disconnecting from maphub
